# Generated by Django 4.2.4 on 2025-07-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("birth_date", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("illness", models.CharField(blank=True, max_length=200, null=True)),
                ("drugs", models.CharField(blank=True, max_length=200, null=True)),
                ("surgical_history", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UpdatedFiles",
            fields=[
                (
                    "updated_file_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="upfated_files/")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "service_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tercih",
                    models.CharField(
                        choices=[
                            ("tahlil", "Tahlil sonucu açıklatmak"),
                            ("soru", "Sağlıkla ilgili soru sormak"),
                            ("oneriler", "Beslenme / egzersiz önerisi almak"),
                            ("hatirlatici", "Hatırlatıcı kurmak"),
                        ],
                        default="tahlil",
                        max_length=20,
                    ),
                ),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                (
                    "calender_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("simple_comment", models.TextField()),
                ("advices", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
    ]
