# Generated by Django 5.2.4 on 2025-07-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_updatedfiles_file_healthquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('patient', 'Patient'), ('ai', 'AI')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.healthquestion')),
            ],
        ),
    ]
