# Generated by Django 5.2.4 on 2025-07-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='app.healthquestion'),
        ),
        migrations.DeleteModel(
            name='HealthMessage',
        ),
    ]
